steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}",
        "-f",
        "./Dockerfile",
        ".",
      ]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"]


images:
  - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"

 - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "patani-ml",
        "--image",
        "gcr.io${PROJECT_ID}/${_SERVICE_NAME}",
        "--region",
        "asia-southeast2",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--port=8080",
        "--port=8501",
        "--args=--model_config_file=/models/model_config.config",
      ]

      