steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/patani-ml", "."]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/patani-ml"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "patani-ml",
        "--image",
        "gcr.io/patani-ch2-ps160/patani-ml",
        "--region",
        "asia-southeast2",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--port=8080",
        "--port=8501",
        "--args=--model_config_file=/models/model_config.config",
      ]
# images:
#   - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:latest"
